const ShopActionTypes = {
    FETCH_COLLCECTIONS_START: 'FETCH_COLLCECTIONS_START',
    FETCH_COLLCECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLCECTIONS_FAILURE: 'FETCH_COLLCECTIONS_FAILURE'
}

export default ShopActionTypes;